name: "Release package"
description: "create and upload packages"
inputs:
  gyg_env:
    required: true
  gyg_region:
    required: true
  version:
    required: true
  branch:
    required: false
  working_directory:
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    
    - run: |
        if ! [[ "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+[\-0-9a-zA-z\.]*$ ]];
        then
          echo "version needs to be of format v*.*.* where * is a digit. e.g. v0.3.2";
          echo "optionally version can have the branch suffixed v*.*.*-branch-name.0";
          exit 1;
        fi
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - env:
        GYG_ENV: ${{ inputs.gyg_env }}
        GYG_REGION: ${{ inputs.gyg_region }}
        RELEASE_VERSION: ${{ inputs.version }}
        BRANCH: ${{ inputs.branch }}
      run: |
        yarn release:build
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - run: |
        echo ${{ github.token }} | gh auth login --with-token
        artifacts=*.zip; msg="Uploading $artifacts to release ${{ inputs.version }}"
        echo $msg
        gh release upload ${{ inputs.version }} *.zip
      shell: bash
      working-directory: ${{ inputs.working_directory }}
